### ISSUE TITLE
server doesnt load option from UnofficialKFPatch

### ISSUE THREAD

**Issue by alfaromeo1991** [GenZmeY/KF2-SafeMutLoader#1]
UnofficialKFPatch option such as ?MaxPlayers= ?PickupLifespan= ?UseDynamicMOTD= ?BroadcastPickups= ?CurrentSeasonalEvent= ?LoadFHUD= ?LoadYAS= ?LoadAAL= ?LoadCVC= will not get applied (I can understand why last 3 wouldn't work tho and i transitioned to using the original mods), other in-game command and stuff seem to be working fine.

**Comment by GenZmeY** [comment]
Oops, I really didn't test this very well.

I'll see what i can do

~~For now, I can suggest using the KFUnofficialPatch.ini config as a temporary solution~~ looks like its not working too ☹️

**Comment by GenZmeY** [comment]
It's sad, but it looks like nothing can be done about it

I updated the description so as not to mislead people, we can assume that Unofficial Patch is partially compatible with SML  

And thanks for reporting the issue anyway

**Comment by GenZmeY** [comment]
Some time ago ForrestMarkX updated their patch and now it is fully compatible with SML, the config reads correctly
