### ISSUE TITLE
[Bug] xp payout

### ISSUE THREAD

**Issue by l3oncoder** [GenZmeY/KF2-SafeMutLoader#2]
Hi there, I'm using the recommended muts you've listed below, my server is showing stats enabled and  tool icon, However the xp gain is crazy low like 1 XP per one kill, any idea's thanks

**Comment by GenZmeY** [comment]
SML doesn't change experience in any way, so it's very strange 😳

the only thing that comes to my mind right now is custom weapons / custom zeds. The game does not give experience if any of these are involved in the kill (but in this case there should be no experience at all, so it's not like what you are describing)

Try adding mutators one by one and see after which mutator the experience problem starts. So we can better understand where the problem begins

**Comment by l3oncoder** [comment]
I have maxplayer mut and reinforced weapons, and the custom zeds for zes spawner

**Comment by GenZmeY** [comment]
Well, that explains everything. This is not a bug.

Experience is given by the [DistributeMoneyAndXP(...)](https://github.com/GenZmeY/KF2-Dev-Scripts/blob/master/KFGame/Classes/KFGameInfo.uc#L2544) function and there is a [ValidateForXP(...)](https://github.com/GenZmeY/KF2-Dev-Scripts/blob/master/KFGame/Classes/KFGameInfo.uc#L2619) that checks if custom zeds and custom damage types are involved in the kill. If yes, experience is not given.
Experience will be awarded if you kill regular zeds with weapons with regular damage type.
(This is how it is implemented in the game, SML does not affect it)

The small experience values you're talking about probably came from damage assist on regular zeds or something like that

To gain experience in all cases, you will have to look for [workarounds](https://github.com/GenZmeY/KF2-SafeMutLoader/blob/master/DEV.md#xp-for-custom-zeds--weapons).
