### ISSUE TITLE
Breaks server query players names are no longer displayed in details

### ISSUE THREAD

**Issue by baztheallmighty** [GenZmeY/KF2-SafeMutLoader#3]
Steps to reproduce with steam:
Run the mod on a server with YAS. 
Open steam -> servers -> select a server running the mod -> view server info.
Normally you should receive a list of users playing in the server. Instead you receive "Server is not responding."

Steps to reproduce with KF2 browser:
Run the mod on a server with YAS. 
Open KF2 -> server browser -> select server running the mod -> server details
Normally you should receive a list of users playing in the server. Instead all players are listed as other platform. 

A wireshark packet capture shows that a packet is being sent in response to the query, however it doesn't contain the names of players currently connected to the server.

**Comment by GenZmeY** [comment]
Yes, you are right. Thanks for the detailed description

I pushed an update with a fix. you can get the latest version of SML here:
https://github.com/GenZmeY/KF2-SafeMutLoader/releases
