### ISSUE TITLE
Any possibility of adding friendly hud as a compatible mutator?

### ISSUE THREAD

**Issue by Stephen720** [GenZmeY/KF2-SafeMutLoader#9]
Thank you for the continued fixes and updates.

I'm aware I can use friendly hud through UKFP but as of recently there seems to be quite a few glitches/bugs with UKFP from players being kicked after a map change to the ready up button not even showing to a few other things.

FriendlyHud being compatible with SML would be awesome if you can make that happen. Either way thanks a tonne for SML and the already long list of compatible mutators.

**Comment by GenZmeY** [comment]
Technically it’s quite simple, but the problem is that need to make changes to FriendlyHUD, and peelz (FriendlyHUD author) left kf2 a long time ago and doesn’t want to return (so it doesn't look like we have the ability to update this mutator)

**Comment by Stephen720** [comment]
Any chance I can add you on discord?

Aren't you allowed to make edits to FriendlyHUD and reupload with credits to the original author? I may be wrong, not sure how the various licences and whatnot work.

**Comment by GenZmeY** [comment]
> Any chance I can add you on discord?

sure! same nickname (genzmey), same avatar

> Aren't you allowed to make edits to FriendlyHUD and reupload with credits to the original author? I may be wrong, not sure how the various licences and whatnot work.

yes it's LGPLv3 so I can

But there are several inconveniences associated with the popularity of this mod. If I post the updated version in the workshop, then many players will often have the problem "FrienldyHUD version mismatch" when switching between servers that use updated version and the original one. They will have to clear the cache every time to avoid this.

There is another way - to post a new version with a changed package name. This will solve the version mismatch problem, but there is another problem: the updated version will not be able to read the old config (and vice versa), players who have already configured fhud will have to live with two versions of the same settings

Maybe I should try contacting peelz again... Still, update peelz workshop item is the best option, it seems to me

**Comment by GenZmeY** [comment]
**PR:** https://github.com/notpeelz/kf2-friendlyhud/pull/2

**Comment by GenZmeY** [comment]
FriendlyHUD is now SML compatible 🎉
